In [1]:
import pandas as pd
import numpy as np 


In [2]:
df = pd.read_csv('spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [5]:
df.shape

(5572, 3)

In [6]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [8]:
X_train.shape

(4457,)

In [9]:
X_test.shape

(1115,)

In [10]:
type(X_train)

pandas.core.series.Series

In [11]:
X_train[:4]

580     Arngd marriage is while u r walkin unfortuntly...
3663    What are you doing in langport? Sorry, but I'l...
3876    Okie but i scared u say i fat... Then u dun wa...
4087                          Lemme know when you're here
Name: Message, dtype: object

In [12]:
type(y_train)

pandas.core.series.Series

In [13]:
y_train[:4]

580     0
3663    0
3876    0
4087    0
Name: spam, dtype: int64

In [14]:
type(X_train.values)

numpy.ndarray

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_CV = v.fit_transform(X_train.values)
X_train_CV

<4457x7770 sparse matrix of type '<class 'numpy.int64'>'
	with 59134 stored elements in Compressed Sparse Row format>

In [16]:
X_train_CV.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [17]:
X_train_CV.shape

(4457, 7770)

In [18]:
v.get_feature_names_out()[1771]

'chat'

In [19]:
v.vocabulary_

{'arngd': 1087,
 'marriage': 4399,
 'is': 3773,
 'while': 7517,
 'walkin': 7387,
 'unfortuntly': 7176,
 'snake': 6307,
 'bites': 1395,
 'bt': 1565,
 'love': 4261,
 'dancing': 2190,
 'in': 3670,
 'frnt': 3051,
 'of': 4925,
 'amp': 966,
 'sayin': 5976,
 'bite': 1394,
 'me': 4442,
 'what': 7499,
 'are': 1068,
 'you': 7731,
 'doing': 2434,
 'langport': 4043,
 'sorry': 6366,
 'but': 1601,
 'll': 4195,
 'probably': 5477,
 'be': 1291,
 'bed': 1308,
 'by': 1616,
 '9pm': 748,
 'it': 3785,
 'sucks': 6605,
 'being': 1330,
 'ill': 3643,
 'at': 1137,
 'xmas': 7676,
 'when': 7506,
 'do': 2410,
 'and': 979,
 'go2sri': 3193,
 'lanka': 4045,
 'okie': 4955,
 'scared': 5984,
 'say': 5974,
 'fat': 2820,
 'then': 6859,
 'dun': 2526,
 'wan': 7396,
 'already': 939,
 'lemme': 4108,
 'know': 3993,
 're': 5641,
 'here': 3448,
 'minimum': 4523,
 'walk': 7384,
 '3miles': 471,
 'day': 2216,
 'havent': 3395,
 'planning': 5278,
 'to': 6966,
 'buy': 1605,
 'later': 4059,
 'check': 1781,
 'lido': 4129,
 'only': 4978,


In [20]:
X_train_np = X_train_CV.toarray()

In [21]:
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [22]:
np.where(X_train_np[0]!=0)

(array([ 966, 1087, 1394, 1395, 1565, 2190, 3051, 3670, 3773, 4261, 4399,
        4442, 4925, 5976, 6307, 7176, 7387, 7517]),)

In [23]:
X_train_np[0][1771]

0

In [24]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_CV, y_train)

MultinomialNB()

In [25]:
X_test_cv = v.transform(X_test)

In [26]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       962
           1       0.99      0.90      0.94       153

    accuracy                           0.98      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.98      0.98      0.98      1115



In [29]:
emails = [
    'hey mohan, can we get together to watch football game tomorrow?',
    'Upto 20% discount on parking, exclusive after just for you. Dont miss this reward'
]

In [30]:
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 0])